In [81]:
import numpy as np 
import pandas as pd
import datetime

In [2]:
df = pd.read_csv("data/GOOG_2019.csv")

In [67]:
df

,Date,Open,High,Low,Close,Adj Close,Volume
0,2019-01-02,1016.570007,1052.319946,1015.710022,1045.849976,1045.849976,1532600
1,2019-01-03,1041.000000,1056.979980,1014.070007,1016.059998,1016.059998,1841100
2,2019-01-04,1032.589966,1070.839966,1027.417969,1070.709961,1070.709961,2093900
3,2019-01-07,1071.500000,1074.000000,1054.760010,1068.390015,1068.390015,1981900
4,2019-01-08,1076.109985,1084.560059,1060.530029,1076.280029,1076.280029,1764900
5,2019-01-09,1081.650024,1082.630005,1066.400024,1074.660034,1074.660034,1199300
6,2019-01-10,1067.660034,1071.150024,1057.709961,1070.329956,1070.329956,1456400
7,2019-01-11,1063.180054,1063.775024,1048.479980,1057.189941,1057.189941,1520800
8,2019-01-14,1046.920044,1051.530029,1041.255005,1044.689941,1044.689941,1144300
9,2019-01-15,1050.170044,1080.050049,1047.339966,1077.150024,1077.150024,1463600
10,2019-01-16,1080.000000,1092.375000,1079.339966,1080.969971,1080.969971,1331800
11,2019-01-17,1079.469971,1091.800049,1073.500000,1089.900024,1089.900024,1242700
12,2019-01-18,1100.000000,1108.352051,1090.900024,1098.260010,1098.260010,1955600
13,2019-01-22,1088.000000,1091.510010,1063.469971,1070.520020,1070.520020,1613500
14,2019-01-23,1077.349976,1084.930054,1059.750000,1075.569946,1075.569946,967000
15,2019-01-24,1076.479980,1079.474976,1060.699951,1073.900024,1073.900024,1361300
16,2019-01-25,1085.000000,1094.000000,1081.819946,1090.989990,1090.989990,1119100
17,2019-01-28,1080.109985,1083.000000,1063.800049,1070.079956,1070.079956,1284300
18,2019-01-29,1072.680054,1075.150024,1055.864990,1060.619995,1060.619995,1021800
19,2019-01-30,1068.430054,1091.000000,1066.849976,1089.060059,1089.060059,1279800
20,2019-01-31,1103.000000,1117.329956,1095.410034,1116.369995,1116.369995,1538300
21,2019-02-01,1112.400024,1125.000000,1104.890015,1110.750000,1110.750000,1462200
22,2019-02-04,1112.660034,1132.800049,1109.020020,1132.800049,1132.800049,2576500
23,2019-02-05,1124.839966,1146.849976,1117.248047,1145.989990,1145.989990,3552200
24,2019-02-06,1139.569946,1147.000000,1112.770020,1115.229980,1115.229980,2105600
25,2019-02-07,1104.160034,1104.839966,1086.000000,1098.709961,1098.709961,2044800
26,2019-02-08,1087.000000,1098.910034,1086.550049,1095.060059,1095.060059,1075800
27,2019-02-11,1096.949951,1105.944946,1092.859985,1095.010010,1095.010010,1065200
28,2019-02-12,1106.800049,1125.295044,1105.849976,1121.369995,1121.369995,1609100
29,2019-02-13,1124.989990,1134.729980,1118.500000,1120.160034,1120.160034,1049800
...,...,...,...,...,...,...,...
221,2019-11-15,1318.939941,1334.880005,1314.280029,1334.869995,1334.869995,1782600
222,2019-11-18,1332.219971,1335.529053,1317.500000,1320.699951,1320.699951,1487400
223,2019-11-19,1327.699951,1327.699951,1312.800049,1315.459961,1315.459961,1269200
224,2019-11-20,1311.739990,1315.000000,1291.150024,1303.050049,1303.050049,1308600
225,2019-11-21,1301.479980,1312.589966,1293.000000,1301.349976,1301.349976,995500
226,2019-11-22,1305.619995,1308.729980,1291.410034,1295.339966,1295.339966,1385700
227,2019-11-25,1299.180054,1311.310059,1298.130005,1306.689941,1306.689941,1036200
228,2019-11-26,1309.859985,1314.800049,1305.089966,1313.550049,1313.550049,1069700
229,2019-11-27,1315.000000,1318.359985,1309.630005,1312.989990,1312.989990,995600
230,2019-11-29,1307.119995,1310.204956,1303.969971,1304.959961,1304.959961,587000
231,2019-12-02,1301.000000,1305.829956,1281.000000,1289.920044,1289.920044,1510900
232,2019-12-03,1279.569946,1298.461060,1279.000000,1295.280029,1295.280029,1143800
233,2019-12-04,1307.010010,1325.800049,1304.869995,1320.540039,1320.540039,1537500
234,2019-12-05,1328.000000,1329.358032,1316.439941,1328.130005,1328.130005,1212700
235,2019-12-06,1333.439941,1344.000000,1333.439941,1340.619995,1340.619995,1314800
236,2019-12-09,1338.040039,1359.449951,1337.839966,1343.560059,1343.560059,1354300
237,2019-12-10,1341.500000,1349.974976,1336.040039,1344.660034,1344.660034,1094100
238,2019-12-11,1350.839966,1351.199951,1342.670044,1345.020020,1345.020020,850400
239,2019-12-12,1345.939941,1355.775024,1340.500000,1350.270020,1350.270020,1281000
240,2019-12-13,1347.949951,1353.093018,1343.869995,1347.829956,1347.829956,1549600
241,2019-12-16,1356.500000,1364.680054,1352.670044,1361.170044,1361.170044,1397300
242,2019-12-17,1362.890015,1365.000000,1351.322998,1355.119995,1355.119995,1854000
243,2019-12-18,1356.599976,1360.469971,1351.000000,1352.619995,1352.619995,1522600
244,2019-12-19,1351.819946,1358.099976,1348.984985,1356.040039,1356.040039,1469900
245,2019-12-20,1363.349976,1363.640015,1349.000000,1349.589966,1349.589966,3315000
246,2019-12-23,1355.869995,1359.800049,1346.510010,1348.839966,1348.839966,883100
247,2019-12-24,1348.500000,1350.260010,1342.780029,1343.560059,1343.560059,347500
248,2019-12-26,1346.170044,1361.327026,1344.469971,1360.400024,1360.400024,667500
249,2019-12-27,1362.989990,1364.530029,1349.310059,1351.890015,1351.890015,1038400
250,2019-12-30,1350.000000,1353.000000,1334.020020,1336.140015,1336.140015,1050900

In [4]:
df1 = pd.read_csv("data/GOOG.csv")

In [66]:
df1

,Date,Open,High,Low,Close,Adj Close,Volume
0,2010-08-12,242.212219,247.622620,241.496490,246.251251,246.251251,4404700
1,2010-08-13,244.744751,245.840836,243.248245,243.418411,243.418411,3865500
2,2010-08-16,242.082077,245.180176,240.490494,243.038040,243.038040,2607300
3,2010-08-17,244.509506,247.597595,243.258255,245.505508,245.505508,3777600
4,2010-08-18,245.465469,245.680679,241.016022,241.316315,241.316315,5367400
5,2010-08-19,240.745743,241.496490,233.858856,234.219223,234.219223,7842100
6,2010-08-20,234.219223,236.031036,230.740738,231.241241,231.241241,7827300
7,2010-08-23,230.980988,234.359360,229.094101,232.267273,232.267273,5966400
8,2010-08-24,229.079086,229.414413,225.685684,225.920914,225.920914,5519800
9,2010-08-25,225.225220,229.134140,225.225220,227.537537,227.537537,5179000
10,2010-08-26,228.258255,228.858856,225.445450,225.715714,225.715714,3550400
11,2010-08-27,226.506500,230.225220,224.049042,229.644638,229.644638,4620100
12,2010-08-30,229.804810,230.110107,226.436432,226.571579,226.571579,2460300
13,2010-08-31,225.280273,227.662659,224.224228,225.235229,225.235229,3889700
14,2010-09-01,227.717712,232.702698,226.476471,230.395401,230.395401,6450100
15,2010-09-02,231.651657,232.447449,230.385391,231.821823,231.821823,3365000
16,2010-09-03,235.495499,236.176178,233.953949,235.385391,235.385391,5075700
17,2010-09-07,232.482483,234.029022,231.741745,232.432434,232.432434,3416300
18,2010-09-08,232.827835,236.486481,232.487488,235.525528,235.525528,4798700
19,2010-09-09,239.154160,240.440445,235.525528,238.328323,238.328323,4856300
20,2010-09-10,239.749756,240.135132,237.777771,238.308304,238.308304,3944600
21,2010-09-13,240.690689,242.417419,240.005005,241.376373,241.376373,4478500
22,2010-09-14,241.246246,242.617615,240.280273,240.455460,240.455460,4428500
23,2010-09-15,240.215210,241.186188,239.489487,240.560562,240.560562,4800700
24,2010-09-16,240.215210,241.466461,239.944946,240.770767,240.770767,3935000
25,2010-09-17,242.117111,245.845840,240.830826,245.320328,245.320328,11271900
26,2010-09-20,246.496490,255.460464,246.276276,254.394394,254.394394,8798100
27,2010-09-21,255.095093,260.250244,254.709717,256.987000,256.987000,8923600
28,2010-09-22,256.686676,259.149139,256.096100,258.258270,258.258270,5069100
29,2010-09-23,257.562561,260.105103,255.905899,256.997009,256.997009,4630100
...,...,...,...,...,...,...,...
1731,2017-06-28,950.659973,963.239990,936.159973,961.010010,961.010010,2745600
1732,2017-06-29,951.349976,951.659973,929.599976,937.820007,937.820007,3206700
1733,2017-06-30,943.989990,945.000000,929.609985,929.679993,929.679993,2287700
1734,2017-07-03,933.219971,934.239990,915.309998,919.460022,919.460022,1694800
1735,2017-07-05,924.200012,936.289978,918.630005,932.260010,932.260010,2094100
1736,2017-07-06,925.000000,936.140015,919.849976,927.690002,927.690002,2014900
1737,2017-07-07,930.989990,944.659973,929.789978,940.809998,940.809998,1663300
1738,2017-07-10,941.950012,953.130005,941.950012,951.000000,951.000000,1451500
1739,2017-07-11,950.520020,954.890015,945.119995,953.530029,953.530029,1461200
1740,2017-07-12,960.859985,969.630005,957.039978,967.659973,967.659973,1602100
1741,2017-07-13,970.799988,978.700012,964.799988,968.849976,968.849976,1524600
1742,2017-07-14,974.000000,977.539978,970.150024,976.909973,976.909973,1079600
1743,2017-07-17,976.320007,983.349976,970.799988,975.960022,975.960022,1660500
1744,2017-07-18,973.359985,990.849976,972.039978,986.950012,986.950012,1413300
1745,2017-07-19,990.010010,995.599976,987.010010,992.770020,992.770020,1412100
1746,2017-07-20,997.000000,998.679993,984.619995,992.190002,992.190002,1418400
1747,2017-07-21,989.000000,995.109985,984.169983,993.840027,993.840027,1463300
1748,2017-07-24,994.099976,1006.190002,990.270020,998.309998,998.309998,3984500
1749,2017-07-25,970.700012,976.729980,963.799988,969.030029,969.030029,5933600
1750,2017-07-26,972.780029,973.950012,960.229980,965.309998,965.309998,2221600
1751,2017-07-27,969.179993,969.520020,937.059998,952.510010,952.510010,3717900
1752,2017-07-28,947.989990,961.789978,945.309998,958.330017,958.330017,1813800
1753,2017-07-31,960.000000,961.190002,941.729980,945.500000,945.500000,2283500
1754,2017-08-01,947.809998,954.489990,944.960022,946.559998,946.559998,1402600
1755,2017-08-02,948.369995,949.099976,932.520020,947.640015,947.640015,2039400
1756,2017-08-03,949.099976,950.000000,939.440002,940.299988,940.299988,1123900
1757,2017-08-04,943.950012,947.539978,939.799988,945.789978,945.789978,1254600
1758,2017-08-07,947.520020,948.960022,943.500000,945.750000,945.750000,1445800
1759,2017-08-08,944.289978,952.489990,942.479980,944.190002,944.190002,1505100
1760,2017-08-09,938.450012,943.760010,933.919983,940.080017,940.080017,1400900

In [64]:
df2 = pd.read_csv("data/GOOG_2018.csv")

In [65]:
df2

,Date,Open,High,Low,Close,Adj Close,Volume
0,2017-08-10,935.000000,936.299988,921.780029,923.590027,923.590027,2707400
1,2017-08-11,923.710022,933.359985,921.219971,930.090027,930.090027,1616700
2,2017-08-14,939.070007,941.039978,934.489990,938.929993,938.929993,1148500
3,2017-08-15,941.030029,943.070007,936.640015,938.080017,938.080017,1106500
4,2017-08-16,941.250000,949.900024,940.039978,944.270020,944.270020,1345300
5,2017-08-17,942.950012,943.809998,927.640015,927.659973,927.659973,1695700
6,2017-08-18,926.979980,931.020020,923.450012,926.179993,926.179993,1337400
7,2017-08-21,925.770020,928.250000,918.599976,920.869995,920.869995,1301200
8,2017-08-22,926.960022,941.960022,926.169983,940.400024,940.400024,1775100
9,2017-08-23,937.000000,945.429993,935.239990,942.580017,942.580017,1134500
10,2017-08-24,943.710022,946.309998,930.739990,936.890015,936.890015,1294600
11,2017-08-25,939.210022,940.729980,930.099976,930.500000,930.500000,1187300
12,2017-08-28,931.880005,934.849976,926.109985,928.130005,928.130005,1049400
13,2017-08-29,919.950012,938.190002,919.309998,935.750000,935.750000,1158600
14,2017-08-30,935.669983,945.859985,934.049988,943.630005,943.630005,1120300
15,2017-08-31,946.299988,957.200012,946.250000,955.239990,955.239990,1693300
16,2017-09-01,957.469971,958.330017,950.280029,951.989990,951.989990,1042900
17,2017-09-05,946.859985,951.390015,935.599976,941.479980,941.479980,1457400
18,2017-09-06,943.869995,944.500000,932.679993,942.020020,942.020020,1391500
19,2017-09-07,944.250000,950.500000,937.530029,949.890015,949.890015,1116600
20,2017-09-08,949.700012,950.700012,940.010010,941.409973,941.409973,999900
21,2017-09-11,947.200012,952.679993,941.000000,943.289978,943.289978,1337400
22,2017-09-12,946.919983,948.090027,937.500000,946.650024,946.650024,1284800
23,2017-09-13,945.500000,952.849976,944.739990,950.440002,950.440002,1095400
24,2017-09-14,946.000000,948.030029,938.359985,940.130005,940.130005,1427400
25,2017-09-15,940.090027,941.750000,931.250000,935.289978,935.289978,1994300
26,2017-09-18,935.010010,936.859985,925.400024,929.750000,929.750000,1473700
27,2017-09-19,933.409973,937.940002,926.659973,936.859985,936.859985,1242700
28,2017-09-20,937.729980,950.000000,937.500000,947.539978,947.539978,2004000
29,2017-09-21,948.130005,952.799988,939.380005,947.549988,947.549988,1370700
...,...,...,...,...,...,...,...
223,2018-06-29,1132.310059,1141.359985,1127.020020,1129.189941,1129.189941,1578100
224,2018-07-02,1115.349976,1142.989990,1106.599976,1142.109985,1142.109985,1160800
225,2018-07-03,1149.420044,1149.910034,1114.430054,1116.280029,1116.280029,822400
226,2018-07-05,1124.599976,1144.140015,1123.119995,1141.290039,1141.290039,1429700
227,2018-07-06,1141.770020,1156.199951,1137.239990,1155.079956,1155.079956,1091000
228,2018-07-09,1160.000000,1167.930054,1157.229980,1167.280029,1167.280029,1079200
229,2018-07-10,1169.989990,1173.500000,1162.560059,1167.140015,1167.140015,1066700
230,2018-07-11,1155.619995,1180.439941,1155.369995,1171.459961,1171.459961,1662600
231,2018-07-12,1174.859985,1201.989990,1173.099976,1201.260010,1201.260010,2207400
232,2018-07-13,1202.800049,1210.439941,1195.290039,1204.420044,1204.420044,1630600
233,2018-07-16,1203.810059,1208.709961,1193.400024,1196.510010,1196.510010,1339200
234,2018-07-17,1182.739990,1218.760010,1182.000000,1213.079956,1213.079956,2008100
235,2018-07-18,1208.530029,1221.589966,1204.560059,1212.910034,1212.910034,1947400
236,2018-07-19,1206.650024,1216.479980,1197.729980,1199.099976,1199.099976,1916900
237,2018-07-20,1199.239990,1210.770020,1196.589966,1197.880005,1197.880005,1896900
238,2018-07-23,1195.660034,1215.099976,1192.010010,1211.000000,1211.000000,3272300
239,2018-07-24,1271.000000,1275.000000,1244.140015,1258.150024,1258.150024,5380000
240,2018-07-25,1252.619995,1278.239990,1249.050049,1275.939941,1275.939941,2555200
241,2018-07-26,1267.180054,1287.400024,1263.000000,1285.500000,1285.500000,2734300
242,2018-07-27,1289.119995,1291.439941,1244.489990,1252.890015,1252.890015,2418100
243,2018-07-30,1245.050049,1252.890015,1224.170044,1230.040039,1230.040039,2194800
244,2018-07-31,1231.709961,1241.209961,1216.189941,1227.219971,1227.219971,1969100
245,2018-08-01,1239.109985,1245.900024,1224.939941,1232.989990,1232.989990,1849700
246,2018-08-02,1218.500000,1244.410034,1218.060059,1241.130005,1241.130005,1735200
247,2018-08-03,1245.180054,1246.520020,1229.420044,1238.160034,1238.160034,1063200
248,2018-08-06,1241.609985,1242.459961,1230.530029,1237.670044,1237.670044,1105700
249,2018-08-07,1252.010010,1266.079956,1251.800049,1255.839966,1255.839966,2125300
250,2018-08-08,1256.719971,1271.719971,1252.119995,1261.329956,1261.329956,1717200
251,2018-08-09,1262.729980,1271.959961,1260.099976,1264.459961,1264.459961,1365700
252,2018-08-10,1259.180054,1261.199951,1247.160034,1252.510010,1252.510010,1330100

In [73]:
big_df = df1.append(df2, ignore_index = True).append(df, ignore_index = True)
big_df

,Date,Open,High,Low,Close,Adj Close,Volume
0,2010-08-12,242.212219,247.622620,241.496490,246.251251,246.251251,4404700
1,2010-08-13,244.744751,245.840836,243.248245,243.418411,243.418411,3865500
2,2010-08-16,242.082077,245.180176,240.490494,243.038040,243.038040,2607300
3,2010-08-17,244.509506,247.597595,243.258255,245.505508,245.505508,3777600
4,2010-08-18,245.465469,245.680679,241.016022,241.316315,241.316315,5367400
5,2010-08-19,240.745743,241.496490,233.858856,234.219223,234.219223,7842100
6,2010-08-20,234.219223,236.031036,230.740738,231.241241,231.241241,7827300
7,2010-08-23,230.980988,234.359360,229.094101,232.267273,232.267273,5966400
8,2010-08-24,229.079086,229.414413,225.685684,225.920914,225.920914,5519800
9,2010-08-25,225.225220,229.134140,225.225220,227.537537,227.537537,5179000
10,2010-08-26,228.258255,228.858856,225.445450,225.715714,225.715714,3550400
11,2010-08-27,226.506500,230.225220,224.049042,229.644638,229.644638,4620100
12,2010-08-30,229.804810,230.110107,226.436432,226.571579,226.571579,2460300
13,2010-08-31,225.280273,227.662659,224.224228,225.235229,225.235229,3889700
14,2010-09-01,227.717712,232.702698,226.476471,230.395401,230.395401,6450100
15,2010-09-02,231.651657,232.447449,230.385391,231.821823,231.821823,3365000
16,2010-09-03,235.495499,236.176178,233.953949,235.385391,235.385391,5075700
17,2010-09-07,232.482483,234.029022,231.741745,232.432434,232.432434,3416300
18,2010-09-08,232.827835,236.486481,232.487488,235.525528,235.525528,4798700
19,2010-09-09,239.154160,240.440445,235.525528,238.328323,238.328323,4856300
20,2010-09-10,239.749756,240.135132,237.777771,238.308304,238.308304,3944600
21,2010-09-13,240.690689,242.417419,240.005005,241.376373,241.376373,4478500
22,2010-09-14,241.246246,242.617615,240.280273,240.455460,240.455460,4428500
23,2010-09-15,240.215210,241.186188,239.489487,240.560562,240.560562,4800700
24,2010-09-16,240.215210,241.466461,239.944946,240.770767,240.770767,3935000
25,2010-09-17,242.117111,245.845840,240.830826,245.320328,245.320328,11271900
26,2010-09-20,246.496490,255.460464,246.276276,254.394394,254.394394,8798100
27,2010-09-21,255.095093,260.250244,254.709717,256.987000,256.987000,8923600
28,2010-09-22,256.686676,259.149139,256.096100,258.258270,258.258270,5069100
29,2010-09-23,257.562561,260.105103,255.905899,256.997009,256.997009,4630100
...,...,...,...,...,...,...,...
2235,2019-11-15,1318.939941,1334.880005,1314.280029,1334.869995,1334.869995,1782600
2236,2019-11-18,1332.219971,1335.529053,1317.500000,1320.699951,1320.699951,1487400
2237,2019-11-19,1327.699951,1327.699951,1312.800049,1315.459961,1315.459961,1269200
2238,2019-11-20,1311.739990,1315.000000,1291.150024,1303.050049,1303.050049,1308600
2239,2019-11-21,1301.479980,1312.589966,1293.000000,1301.349976,1301.349976,995500
2240,2019-11-22,1305.619995,1308.729980,1291.410034,1295.339966,1295.339966,1385700
2241,2019-11-25,1299.180054,1311.310059,1298.130005,1306.689941,1306.689941,1036200
2242,2019-11-26,1309.859985,1314.800049,1305.089966,1313.550049,1313.550049,1069700
2243,2019-11-27,1315.000000,1318.359985,1309.630005,1312.989990,1312.989990,995600
2244,2019-11-29,1307.119995,1310.204956,1303.969971,1304.959961,1304.959961,587000
2245,2019-12-02,1301.000000,1305.829956,1281.000000,1289.920044,1289.920044,1510900
2246,2019-12-03,1279.569946,1298.461060,1279.000000,1295.280029,1295.280029,1143800
2247,2019-12-04,1307.010010,1325.800049,1304.869995,1320.540039,1320.540039,1537500
2248,2019-12-05,1328.000000,1329.358032,1316.439941,1328.130005,1328.130005,1212700
2249,2019-12-06,1333.439941,1344.000000,1333.439941,1340.619995,1340.619995,1314800
2250,2019-12-09,1338.040039,1359.449951,1337.839966,1343.560059,1343.560059,1354300
2251,2019-12-10,1341.500000,1349.974976,1336.040039,1344.660034,1344.660034,1094100
2252,2019-12-11,1350.839966,1351.199951,1342.670044,1345.020020,1345.020020,850400
2253,2019-12-12,1345.939941,1355.775024,1340.500000,1350.270020,1350.270020,1281000
2254,2019-12-13,1347.949951,1353.093018,1343.869995,1347.829956,1347.829956,1549600
2255,2019-12-16,1356.500000,1364.680054,1352.670044,1361.170044,1361.170044,1397300
2256,2019-12-17,1362.890015,1365.000000,1351.322998,1355.119995,1355.119995,1854000
2257,2019-12-18,1356.599976,1360.469971,1351.000000,1352.619995,1352.619995,1522600
2258,2019-12-19,1351.819946,1358.099976,1348.984985,1356.040039,1356.040039,1469900
2259,2019-12-20,1363.349976,1363.640015,1349.000000,1349.589966,1349.589966,3315000
2260,2019-12-23,1355.869995,1359.800049,1346.510010,1348.839966,1348.839966,883100
2261,2019-12-24,1348.500000,1350.260010,1342.780029,1343.560059,1343.560059,347500
2262,2019-12-26,1346.170044,1361.327026,1344.469971,1360.400024,1360.400024,667500
2263,2019-12-27,1362.989990,1364.530029,1349.310059,1351.890015,1351.890015,1038400
2264,2019-12-30,1350.000000,1353.000000,1334.020020,1336.140015,1336.140015,1050900

In [135]:
def add_tech_ind(df):
    df = df.copy()
    def ma(arr, n):
        if n == 1:
            return arr
        else:
            result = [0 for i in range(n - 1)]
            result1 = arr[:-n + 1].copy()
            length = len(arr)
            for i in range(1, n):
                result1 += arr[i:length + 1 - n + i]
            result1 /= n
            result += list(result1)
            return np.array(result)
    
    def ema(arr, n):
        if n == 1:
            return arr
        else:
            result = []
            for i in range(len(arr)):
                temp = arr[i]
                if i == 0:
                    result.append(temp)
                else:
                    temp = 2 / (1 + n) * temp
                    temp += (1 - 2 / (1 + n)) * result[-1]
                    result.append(temp)
            return np.array(result)
        
    
    def add_ma_ret(df):
        ''' add ma of return calculated by closing price '''
        cps = df.loc[:,'Close'].values
        cps = np.array([float(val) for val in cps])
        ret = cps[1:] / cps[:-1] - 1.0
        ret1 = [0.0] + list(ret)
        df['ret1'] = ret1
        ret1  = np.array(ret1)
        ret2 = [0.0] + list((ret1[1:] + ret1[:-1]) / 2)
        df['ret2'] = ma(ret1, 2)
        df['ret4'] = ma(ret1, 4)
        df['ret8'] = ma(ret1, 8)
        df['ret16'] = ma(ret1, 16)
        
        
    def add_ma_vol(df):
        ''' add ma of volume '''
        vol = df.loc[:, 'Volume'].values
        vol = np.array([float(val) for val in vol], dtype = 'float')
        df['vol2'] = ma(vol, 2)
        df['vol4'] = ma(vol, 4)
        df['vol8'] = ma(vol, 8)
        df['vol16'] = ma(vol, 16)
        
    def add_weekday_dummyvar(df):
        ''' add what week day it is '''
        dates = df['Date'].values
        dates = [datetime.date(int(val[:4]), int(val[5:7]), int(val[8:])) for val in dates]
        weekday = [(val.weekday() == 0 or val.weekday() == 4)  for val in dates]
        result = np.zeros(len(df))
        result[weekday] = 1
        df['weekday'] = result
        
    def add_subline(df):
        ''' add k-line subline '''
        length = len(df)
        result = np.ones(length)
        cps = df.loc[:,'Close'].values
        cps = np.array([float(val) for val in cps])
        ops = df.loc[:,'Open'].values
        ops = np.array([float(val) for val in ops])
        lows = df.loc[:,'Low'].values
        lows = np.array([float(val) for val in lows])
        result = np.min(np.vstack((ops, cps)), axis = 0)
        df['sub'] = (result - lows) / cps
        df['sub2'] = ma((result - lows) / cps, 2)
        df['sub4'] = ma((result - lows) / cps, 4)
        df['sub8'] = ma((result - lows) / cps, 8)
        df['sub16'] = ma((result - lows) / cps, 16)
        
    def add_macd(df):
        ''' add MACD '''
        cps = df.loc[:,'Close'].values
        cps = np.array([float(val) for val in cps])
        df['MACD'] = ema(cps, 12) - ema(cps, 26)
        
    def add_bbbb_day(df):
        ''' add bbbb in day '''
        cps = df.loc[:,'Close'].values
        cps = np.array([float(val) for val in cps])
        ops = df.loc[:,'Open'].values
        ops = np.array([float(val) for val in ops])
        lows = df.loc[:,'Low'].values
        lows = np.array([float(val) for val in lows])
        highs = df.loc[:,'High'].values
        highs = np.array([float(val) for val in highs])
        df['bbbb_day'] = (highs + lows) - 2 * cps
    
    def add_cccc_day(df):
        ''' add cccc in day '''
        cps = df.loc[:,'Close'].values
        cps = np.array([float(val) for val in cps])
        ops = df.loc[:,'Open'].values
        ops = np.array([float(val) for val in ops])
        lows = df.loc[:,'Low'].values
        lows = np.array([float(val) for val in lows])
        highs = df.loc[:,'High'].values
        highs = np.array([float(val) for val in highs])
        df['cccc_day'] = (highs - lows) / 2 / cps
        
    def add_kdj(df):
        ''' add kdj '''
        cps = df.loc[:,'Close'].values
        cps = np.array([float(val) for val in cps])
        ops = df.loc[:,'Open'].values
        ops = np.array([float(val) for val in ops])
        lows = df.loc[:,'Low'].values
        lows = np.array([float(val) for val in lows])
        highs = df.loc[:,'High'].values
        highs = np.array([float(val) for val in highs])
        K = np.zeros(len(df))
        for i in range(len(df)):
            start = max(i - 4, 0)
            end = i + 1
            K[i] = (cps[i] - np.min(lows[start:end])) / (np.max(highs[start:end]) - np.min(lows[start:end]))
        D = ema(K, 3)
        df['K'] = K
        df['D'] = D
    
    add_ma_ret(df)
    add_ma_vol(df)
    add_weekday_dummyvar(df)
    add_subline(df)
    add_macd(df)
    add_bbbb_day(df)
    add_cccc_day(df)
    add_kdj(df)
    return df

In [139]:
to_save = add_tech_ind(big_df)
to_save[:1761].to_csv('data/GOOG_mod.csv', index = False)
to_save[1761: 1761 + 253].to_csv('data/GOOG_2018mod.csv', index = False)
to_save[1761 + 253: 1761 + 253 + 251].to_csv('data/GOOG_2019mod.csv', index = False)

In [145]:
to_save.loc[:, 'Open':].values

array([[2.42212219e+02, 2.47622620e+02, 2.41496490e+02, ...,
        1.24387794e-02, 7.76144319e-01, 7.76144319e-01],
       [2.44744751e+02, 2.45840836e+02, 2.43248245e+02, ...,
        5.32537985e-03, 3.13725141e-01, 5.44934730e-01],
       [2.42082077e+02, 2.45180176e+02, 2.40490494e+02, ...,
        9.64804111e-03, 3.57193073e-01, 4.51063901e-01],
       ...,
       [1.34617004e+03, 1.36132703e+03, 1.34446997e+03, ...,
        6.19562434e-03, 8.44679138e-01, 4.85941802e-01],
       [1.36298999e+03, 1.36453003e+03, 1.34931006e+03, ...,
        5.62914506e-03, 4.18849931e-01, 4.52395867e-01],
       [1.35000000e+03, 1.35300000e+03, 1.33402002e+03, ...,
        7.10254157e-03, 6.94852302e-02, 2.60940548e-01]])

In [148]:
to_save.loc[0]

Date         2010-08-12
Open            242.212
High            247.623
Low             241.496
Close           246.251
Adj Close       246.251
Volume          4404700
ret1                  0
ret2                  0
ret4                  0
ret8                  0
ret16                 0
vol2                  0
vol4                  0
vol8                  0
vol16                 0
weekday               0
sub           0.0029065
sub2                  0
sub4                  0
sub8                  0
sub16                 0
MACD                  0
bbbb_day       -3.38339
cccc_day      0.0124388
K              0.776144
D              0.776144
Name: 0, dtype: object

In [87]:
big_df['Date'].values

array(['2010-08-12', '2010-08-13', '2010-08-16', ..., '2019-12-26',
       '2019-12-27', '2019-12-30'], dtype=object)

In [84]:
np.ones(3)[:-0]

array([], dtype=float64)

In [52]:
0.0005646 * 4

0.0022584

In [108]:
1 / 240

0.004166666666666667